server:
  port: 8090
mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.example.demo.Entity
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1;DatabaseName=GPEA
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456